// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PontoPlus.Manager.Infra.Data;

namespace PontoPlus.Migrations
{
    [DbContext(typeof(PontoPlusContext))]
    [Migration("20211018154143_AddUsuarioMensagemEntity")]
    partial class AddUsuarioMensagemEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("PontoPlus.Manager.Domain.Entities.RegistroPonto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Saida")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("TotalTempo")
                        .HasColumnType("time(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistroPontos");
                });

            modelBuilder.Entity("PontoPlus.Manager.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Departamentos")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<TimeSpan>("EntradaAm")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("EntradaPm")
                        .HasColumnType("time(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<TimeSpan>("SaidaAm")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("SaidaPm")
                        .HasColumnType("time(6)");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PontoPlus.Manager.Domain.Entities.UsuarioMensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.ToTable("UsuarioMensagens");
                });

            modelBuilder.Entity("PontoPlus.Manager.Domain.Entities.RegistroPonto", b =>
                {
                    b.HasOne("PontoPlus.Manager.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Pontos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PontoPlus.Manager.Domain.Entities.UsuarioMensagem", b =>
                {
                    b.HasOne("PontoPlus.Manager.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Mensagens")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PontoPlus.Manager.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Mensagens");

                    b.Navigation("Pontos");
                });
#pragma warning restore 612, 618
        }
    }
}
